"""Add google_id and avatar_url to user table

Revision ID: fba210460bdc
Revises: 6db199ffe467
Create Date: 2026-04-03 14:17:50.272231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'fba210460bdc'
down_revision: Union[str, None] = '6db199ffe467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('records_created_by_fkey', 'records', type_='foreignkey')
    op.drop_constraint('records_updated_by_fkey', 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'records', 'users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key('records_updated_by_fkey', 'records', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('records_created_by_fkey', 'records', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
